In [4]:
deliveries = pd.read_csv(r"C:\Users\ADMIN\Downloads\deliveries.csv")

In [2]:
import pandas as pd
import numpy as np

In [5]:
deliveries

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179073,11415,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,SR Watson,SL Malinga,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179074,11415,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179075,11415,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,1,0,1,SR Watson,run out,KH Pandya
179076,11415,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179077,11415,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,0,0,0,SN Thakur,lbw,NaN

In [20]:
match.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 756 entries, 0 to 755
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   match_id         756 non-null    int64
 1   season           756 non-null    int64
 2   city             749 non-null    object
 3   date             756 non-null    object
 4   team1            756 non-null    object
 5   team2            756 non-null    object
 6   toss_winner      756 non-null    object
 7   toss_decision    756 non-null    object
 8   result           756 non-null    object
 9   dl_applied       756 non-null    int64
 10  winner           752 non-null    object
 11  win_by_runs      756 non-null    int64
 12  win_by_wickets   756 non-null    int64
 13  player_of_match  752 non-null    object
 14  venue            756 non-null    object
 15  umpire1          754 non-null    object
 16  umpire2          754 non-null    object
 17  umpire3          119 non-null    object
dtypes: int64(5), object(13)
memory usage: 106.4+ KB

In [9]:
deliveries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 179078 entries, 0 to 179077
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          179078 non-null  int64
 1   inning            179078 non-null  int64
 2   batting_team      179078 non-null  object
 3   bowling_team      179078 non-null  object
 4   over              179078 non-null  int64
 5   ball              179078 non-null  int64
 6   batsman           179078 non-null  object
 7   non_striker       179078 non-null  object
 8   bowler            179078 non-null  object
 9   is_super_over     179078 non-null  int64
 10  wide_runs         179078 non-null  int64
 11  bye_runs          179078 non-null  int64
 12  legbye_runs       179078 non-null  int64
 13  noball_runs       179078 non-null  int64
 14  penalty_runs      179078 non-null  int64
 15  batsman_runs      179078 non-null  int64
 16  extra_runs        179078 non-null  int64
 17  total_runs        179078 non-null  int64
 18  player_dismissed  8834 non-null    object
 19  dismissal_kind    8834 non-null    object
 20  fielder           6448 non-null    object
dtypes: int64(13), object(8)
memory usage: 28.7+ MB

In [6]:
match = pd.read_csv(r"C:\Users\ADMIN\Downloads\matches.csv")

In [7]:
match

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,11347,2019,Mumbai,05/05/19,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,9,HH Pandya,Wankhede Stadium,Nanda Kishore,O Nandan,S Ravi
752,11412,2019,Chennai,07/05/19,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,bat,normal,0,Mumbai Indians,0,6,AS Yadav,M. A. Chidambaram Stadium,Nigel Llong,Nitin Menon,Ian Gould
753,11413,2019,Visakhapatnam,08/05/19,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,normal,0,Delhi Capitals,0,2,RR Pant,ACA-VDCA Stadium,NaN,NaN,NaN
754,11414,2019,Visakhapatnam,10/05/19,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,6,F du Plessis,ACA-VDCA Stadium,Sundaram Ravi,Bruce Oxenford,Chettithody Shamshuddin
755,11415,2019,Hyderabad,12/05/19,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Mumbai Indians,1,0,JJ Bumrah,Rajiv Gandhi Intl. Cricket Stadium,Nitin Menon,Ian Gould,Nigel Llong

In [11]:
match.rename(columns={'id': 'match_id'}, inplace=True)

In [12]:
match

,match_id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,11347,2019,Mumbai,05/05/19,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,9,HH Pandya,Wankhede Stadium,Nanda Kishore,O Nandan,S Ravi
752,11412,2019,Chennai,07/05/19,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,bat,normal,0,Mumbai Indians,0,6,AS Yadav,M. A. Chidambaram Stadium,Nigel Llong,Nitin Menon,Ian Gould
753,11413,2019,Visakhapatnam,08/05/19,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,normal,0,Delhi Capitals,0,2,RR Pant,ACA-VDCA Stadium,NaN,NaN,NaN
754,11414,2019,Visakhapatnam,10/05/19,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,6,F du Plessis,ACA-VDCA Stadium,Sundaram Ravi,Bruce Oxenford,Chettithody Shamshuddin
755,11415,2019,Hyderabad,12/05/19,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Mumbai Indians,1,0,JJ Bumrah,Rajiv Gandhi Intl. Cricket Stadium,Nitin Menon,Ian Gould,Nigel Llong

In [69]:
merged_data = pd.merge(deliveries, match, how="outer", on='match_id')

In [37]:
merged_data

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179073,11415,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,SR Watson,SL Malinga,0,...,normal,0,Mumbai Indians,1,0,JJ Bumrah,Rajiv Gandhi Intl. Cricket Stadium,Nitin Menon,Ian Gould,Nigel Llong
179074,11415,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,RA Jadeja,SL Malinga,0,...,normal,0,Mumbai Indians,1,0,JJ Bumrah,Rajiv Gandhi Intl. Cricket Stadium,Nitin Menon,Ian Gould,Nigel Llong
179075,11415,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,RA Jadeja,SL Malinga,0,...,normal,0,Mumbai Indians,1,0,JJ Bumrah,Rajiv Gandhi Intl. Cricket Stadium,Nitin Menon,Ian Gould,Nigel Llong
179076,11415,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,RA Jadeja,SL Malinga,0,...,normal,0,Mumbai Indians,1,0,JJ Bumrah,Rajiv Gandhi Intl. Cricket Stadium,Nitin Menon,Ian Gould,Nigel Llong
179077,11415,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,RA Jadeja,SL Malinga,0,...,normal,0,Mumbai Indians,1,0,JJ Bumrah,Rajiv Gandhi Intl. Cricket Stadium,Nitin Menon,Ian Gould,Nigel Llong

In [91]:
merged_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 179078 entries, 0 to 179077
Data columns (total 38 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          179078 non-null  int64
 1   inning            179078 non-null  int64
 2   batting_team      179078 non-null  object
 3   bowling_team      179078 non-null  object
 4   over              179078 non-null  int64
 5   ball              179078 non-null  int64
 6   batsman           179078 non-null  object
 7   non_striker       179078 non-null  object
 8   bowler            179078 non-null  object
 9   is_super_over     179078 non-null  int64
 10  wide_runs         179078 non-null  int64
 11  bye_runs          179078 non-null  int64
 12  legbye_runs       179078 non-null  int64
 13  noball_runs       179078 non-null  int64
 14  penalty_runs      179078 non-null  int64
 15  batsman_runs      179078 non-null  int64
 16  extra_runs        179078 non-null  int64
 17  total_runs        179078 non-null  int64
 18  player_dismissed  8834 non-null    object
 19  dismissal_kind    8834 non-null    object
 20  fielder           6448 non-null    object
 21  season            179078 non-null  int64
 22  city              177378 non-null  object
 23  date              179078 non-null  datetime64[ns]
 24  team1             179078 non-null  object
 25  team2             179078 non-null  object
 26  toss_winner       179078 non-null  object
 27  toss_decision     179078 non-null  object
 28  result            179078 non-null  object
 29  dl_applied        179078 non-null  int64
 30  winner            178706 non-null  object
 31  win_by_runs       179078 non-null  int64
 32  win_by_wickets    179078 non-null  int64
 33  player_of_match   178706 non-null  object
 34  venue             179078 non-null  object
 35  umpire1           178578 non-null  object
 36  umpire2           178578 non-null  object
 37  umpire3           28366 non-null   object
dtypes: datetime64[ns](1), int64(17), object(20)
memory usage: 53.3+ MB

In [39]:
merged_data["city"].value_counts()

Mumbai            24302
Kolkata           17991
Delhi             17305
Hyderabad         15215
Bangalore         15155
Chennai           13895
Jaipur            11158
Chandigarh        10840
Pune               9119
Durban             3643
Bengaluru          3248
Visakhapatnam      3037
Ahmedabad          2893
Centurion          2866
Mohali             2431
Rajkot             2381
Dharamsala         2159
Indore             1965
Johannesburg       1940
Cuttack            1695
Port Elizabeth     1677
Ranchi             1671
Abu Dhabi          1624
Cape Town          1539
Sharjah            1439
Raipur             1431
Kochi              1155
Kanpur              921
Nagpur              742
Kimberley           726
East London         715
Bloemfontein        500
Name: city, dtype: int64

In [40]:
merged_data["date"].value_counts()

2009-04-23    513
2017-04-29    508
2013-04-16    506
2012-05-05    506
2014-05-19    503
             ...
2008-05-16    136
2015-04-29    128
2015-05-13    126
2015-05-15    106
30/04/19       51
Name: date, Length: 546, dtype: int64

In [70]:
merged_data['date'] = merged_data['date'].str.replace("/","-")

In [71]:
merged_data['date'].unique()

array(['2017-04-05', '2017-04-06', '2017-04-07', '2017-04-08',
       '2017-04-09', '2017-04-10', '2017-04-11', '2017-04-12',
       '2017-04-13', '2017-04-14', '2017-04-15', '2017-04-16',
       '2017-04-17', '2017-04-18', '2017-04-19', '2017-04-20',
       '2017-04-21', '2017-04-22', '2017-04-23', '2017-04-24',
       '2017-04-26', '2017-04-27', '2017-04-28', '2017-04-29',
       '2017-04-30', '2017-05-01', '2017-05-02', '2017-05-03',
       '2017-05-04', '2017-05-05', '2017-05-06', '2017-05-07',
       '2017-05-08', '2017-05-09', '2017-05-10', '2017-05-11',
       '2017-05-12', '2017-05-13', '2017-05-14', '2017-05-16',
       '2017-05-17', '2017-05-19', '2017-05-21', '2008-04-18',
       '2008-04-19', '2008-04-20', '2008-04-21', '2008-04-22',
       '2008-04-23', '2008-04-24', '2008-04-25', '2008-04-26',
       '2008-04-27', '2008-04-28', '2008-04-29', '2008-04-30',
       '2008-05-01', '2008-05-02', '2008-05-25', '2008-05-03',
       '2008-05-04', '2008-05-05', '2008-05-06', '2008-05-07',
       '2008-05-08', '2008-05-09', '2008-05-28', '2008-05-10',
       '2008-05-11', '2008-05-12', '2008-05-13', '2008-05-14',
       '2008-05-15', '2008-05-16', '2008-05-17', '2008-05-18',
       '2008-05-19', '2008-05-20', '2008-05-21', '2008-05-23',
       '2008-05-24', '2008-05-26', '2008-05-27', '2008-05-30',
       '2008-05-31', '2008-06-01', '2009-04-18', '2009-04-19',
       '2009-04-20', '2009-04-21', '2009-04-22', '2009-04-23',
       '2009-04-24', '2009-04-25', '2009-04-26', '2009-04-27',
       '2009-04-28', '2009-04-29', '2009-04-30', '2009-05-01',
       '2009-05-02', '2009-05-03', '2009-05-04', '2009-05-05',
       '2009-05-06', '2009-05-07', '2009-05-08', '2009-05-09',
       '2009-05-10', '2009-05-11', '2009-05-12', '2009-05-13',
       '2009-05-14', '2009-05-15', '2009-05-16', '2009-05-17',
       '2009-05-18', '2009-05-19', '2009-05-20', '2009-05-21',
       '2009-05-22', '2009-05-23', '2009-05-24', '2010-03-12',
       '2010-03-13', '2010-03-14', '2010-03-15', '2010-03-16',
       '2010-03-17', '2010-03-18', '2010-03-19', '2010-03-20',
       '2010-03-21', '2010-03-22', '2010-03-23', '2010-03-24',
       '2010-03-25', '2010-03-26', '2010-03-27', '2010-03-28',
       '2010-03-29', '2010-03-30', '2010-03-31', '2010-04-01',
       '2010-04-02', '2010-04-03', '2010-04-04', '2010-04-05',
       '2010-04-06', '2010-04-07', '2010-04-08', '2010-04-09',
       '2010-04-10', '2010-04-11', '2010-04-12', '2010-04-13',
       '2010-04-14', '2010-04-15', '2010-04-16', '2010-04-17',
       '2010-04-18', '2010-04-19', '2010-04-21', '2010-04-22',
       '2010-04-24', '2010-04-25', '2011-04-08', '2011-04-09',
       '2011-04-10', '2011-04-11', '2011-04-12', '2011-04-13',
       '2011-04-14', '2011-04-15', '2011-04-16', '2011-04-17',
       '2011-04-18', '2011-04-19', '2011-04-20', '2011-04-21',
       '2011-04-22', '2011-04-23', '2011-04-24', '2011-04-25',
       '2011-04-26', '2011-04-27', '2011-04-28', '2011-04-29',
       '2011-04-30', '2011-05-01', '2011-05-02', '2011-05-03',
       '2011-05-04', '2011-05-05', '2011-05-06', '2011-05-07',
       '2011-05-08', '2011-05-09', '2011-05-10', '2011-05-11',
       '2011-05-12', '2011-05-13', '2011-05-14', '2011-05-15',
       '2011-05-16', '2011-05-17', '2011-05-18', '2011-05-19',
       '2011-05-20', '2011-05-21', '2011-05-22', '2011-05-24',
       '2011-05-25', '2011-05-27', '2011-05-28', '2012-04-04',
       '2012-04-05', '2012-04-06', '2012-04-07', '2012-04-08',
       '2012-04-09', '2012-04-10', '2012-04-11', '2012-04-12',
       '2012-04-13', '2012-04-19', '2012-04-14', '2012-04-15',
       '2012-04-16', '2012-04-17', '2012-04-18', '2012-05-10',
       '2012-04-20', '2012-04-21', '2012-04-22', '2012-04-23',
       '2012-04-24', '2012-04-25', '2012-04-26', '2012-04-27',
       '2012-04-28', '2012-04-29', '2012-04-30', '2012-05-01',
       '2012-05-02', '2012-05-03', '2012-05-04', '2012-05-05',
       '2012-05-06', '2012-05-07', '2012-05-08', '2012-05-09',
       '2012-05-11', '2012-05-12', '2012-05-13', '2012-05-14',
       '2012-05-15', '2012-05-16', '2012-05-17', '2012-05-18',
       '2012-05-19', '2012-05-20', '2012-05-22', '2012-05-23',
       '2012-05-25', '2012-05-27', '2013-04-03', '2013-04-04',
       '2013-04-05', '2013-04-06', '2013-04-07', '2013-04-08',
       '2013-04-09', '2013-04-10', '2013-04-11', '2013-04-12',
       '2013-04-13', '2013-04-14', '2013-04-15', '2013-04-16',
       '2013-04-17', '2013-04-18', '2013-04-19', '2013-04-20',
       '2013-04-21', '2013-04-22', '2013-04-23', '2013-05-16',
       '2013-04-24', '2013-04-25', '2013-04-26', '2013-04-27',
       '2013-04-28', '2013-04-29', '2013-04-30', '2013-05-01',
       '2013-05-02', '2013-05-03', '2013-05-04', '2013-05-14',
       '2013-05-05', '2013-05-07', '2013-05-08', '2013-05-09',
       '2013-05-10', '2013-05-11', '2013-05-12', '2013-05-13',
       '2013-05-15', '2013-05-06', '2013-05-17', '2013-05-18',
       '2013-05-19', '2013-05-21', '2013-05-22', '2013-05-24',
       '2013-05-26', '2014-04-16', '2014-04-17', '2014-04-18',
       '2014-04-19', '2014-04-20', '2014-04-21', '2014-04-22',
       '2014-04-23', '2014-04-24', '2014-04-25', '2014-04-26',
       '2014-04-27', '2014-04-28', '2014-04-29', '2014-04-30',
       '2014-05-02', '2014-05-03', '2014-05-04', '2014-05-05',
       '2014-05-06', '2014-05-07', '2014-05-08', '2014-05-09',
       '2014-05-10', '2014-05-11', '2014-05-12', '2014-05-13',
       '2014-05-14', '2014-05-15', '2014-05-18', '2014-05-19',
       '2014-05-20', '2014-05-21', '2014-05-22', '2014-05-23',
       '2014-05-24', '2014-05-25', '2014-05-27', '2014-05-28',
       '2014-05-30', '2014-06-01', '2015-04-08', '2015-04-09',
       '2015-04-10', '2015-04-11', '2015-04-12', '2015-04-13',
       '2015-04-14', '2015-04-30', '2015-04-15', '2015-04-16',
       '2015-04-17', '2015-04-18', '2015-04-19', '2015-04-20',
       '2015-04-21', '2015-04-22', '2015-04-23', '2015-04-24',
       '2015-04-25', '2015-04-26', '2015-04-27', '2015-05-07',
       '2015-04-29', '2015-04-28', '2015-05-01', '2015-05-02',
       '2015-05-03', '2015-05-04', '2015-05-05', '2015-05-06',
       '2015-05-08', '2015-05-09', '2015-05-10', '2015-05-11',
       '2015-05-12', '2015-05-13', '2015-05-14', '2015-05-15',
       '2015-05-16', '2015-05-17', '2015-05-19', '2015-05-20',
       '2015-05-22', '2015-05-24', '2016-04-09', '2016-04-10',
       '2016-04-11', '2016-04-12', '2016-04-13', '2016-04-14',
       '2016-04-15', '2016-04-16', '2016-04-17', '2016-04-18',
       '2016-04-19', '2016-04-20', '2016-04-21', '2016-04-22',
       '2016-04-23', '2016-04-24', '2016-04-25', '2016-04-26',
       '2016-04-27', '2016-04-28', '2016-04-29', '2016-04-30',
       '2016-05-01', '2016-05-02', '2016-05-03', '2016-05-04',
       '2016-05-05', '2016-05-06', '2016-05-07', '2016-05-08',
       '2016-05-09', '2016-05-10', '2016-05-11', '2016-05-12',
       '2016-05-13', '2016-05-14', '2016-05-15', '2016-05-16',
       '2016-05-17', '2016-05-18', '2016-05-19', '2016-05-20',
       '2016-05-21', '2016-05-22', '2016-05-24', '2016-05-25',
       '2016-05-27', '2016-05-29', '07-04-18', '08-04-18', '09-04-18',
       '10-04-18', '11-04-18', '12-04-18', '13-04-18', '14-04-18',
       '15-04-18', '16-04-18', '17-04-18', '18-04-18', '19-04-18',
       '20-04-18', '21-04-18', '22-04-18', '23-04-18', '24-04-18',
       '25-04-18', '26-04-18', '27-04-18', '28-04-18', '29-04-18',
       '30-04-18', '01-05-18', '02-05-18', '03-05-18', '04-05-18',
       '05-05-18', '06-05-18', '07-05-18', '08-05-18', '09-05-18',
       '10-05-18', '11-05-18', '12-05-18', '13-05-18', '14-05-18',
       '15-05-18', '16-05-18', '17-05-18', '18-05-18', '19-05-18',
       '20-05-18', '22-05-18', '23-05-18', '25-05-18', '27-05-18',
       '23-03-19', '24-03-19', '25-03-19', '26-03-19', '27-03-19',
       '28-03-19', '29-03-19', '30-03-19', '31-03-19', '01-04-19',
       '02-04-19', '03-04-19', '04-04-19', '05-04-19', '06-04-19',
       '07-04-19', '08-04-19', '09-04-19', '10-04-19', '11-04-19',
       '12-04-19', '13-04-19', '14-04-19', '15-04-19', '16-04-19',
       '17-04-19', '18-04-19', '19-04-19', '20-04-19', '21-04-19',
       '22-04-19', '23-04-19', '24-04-19', '25-04-19', '26-04-19',
       '27-04-19', '28-04-19', '29-04-19', '30-04-19', '01-05-19',
       '02-05-19', '03-05-19', '04-05-19', '05-05-19', '07-05-19',
       '08-05-19', '10-05-19', '12-05-19'], dtype=object)

In [78]:
merged_data['date']= pd.to_datetime(merged_data['date'])

In [92]:
merged_data['date']

0        2017-04-05
1        2017-04-05
2        2017-04-05
3        2017-04-05
4        2017-04-05
            ...
179073   2019-12-05
179074   2019-12-05
179075   2019-12-05
179076   2019-12-05
179077   2019-12-05
Name: date, Length: 179078, dtype: datetime64[ns]

In [82]:
merged_data['date'].dt.year.max()

2019

In [101]:
merged_data.loc[(merged_data['date'].dt.year == 2011) & (merged_data["winner"] == "Mumbai Indians") ]

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
56181,238,1,Delhi Daredevils,Mumbai Indians,1,1,DA Warner,V Sehwag,Harbhajan Singh,0,...,normal,0,Mumbai Indians,0,8,SL Malinga,Feroz Shah Kotla,AM Saheba,RB Tiffin,NaN
56182,238,1,Delhi Daredevils,Mumbai Indians,1,2,DA Warner,V Sehwag,Harbhajan Singh,0,...,normal,0,Mumbai Indians,0,8,SL Malinga,Feroz Shah Kotla,AM Saheba,RB Tiffin,NaN
56183,238,1,Delhi Daredevils,Mumbai Indians,1,3,V Sehwag,DA Warner,Harbhajan Singh,0,...,normal,0,Mumbai Indians,0,8,SL Malinga,Feroz Shah Kotla,AM Saheba,RB Tiffin,NaN
56184,238,1,Delhi Daredevils,Mumbai Indians,1,4,V Sehwag,DA Warner,Harbhajan Singh,0,...,normal,0,Mumbai Indians,0,8,SL Malinga,Feroz Shah Kotla,AM Saheba,RB Tiffin,NaN
56185,238,1,Delhi Daredevils,Mumbai Indians,1,5,V Sehwag,DA Warner,Harbhajan Singh,0,...,normal,0,Mumbai Indians,0,8,SL Malinga,Feroz Shah Kotla,AM Saheba,RB Tiffin,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71968,305,2,Mumbai Indians,Kolkata Knight Riders,19,4,JEC Franklin,Harbhajan Singh,B Lee,0,...,normal,0,Mumbai Indians,0,4,MM Patel,Wankhede Stadium,Asad Rauf,SJA Taufel,NaN
71969,305,2,Mumbai Indians,Kolkata Knight Riders,19,5,JEC Franklin,Harbhajan Singh,B Lee,0,...,normal,0,Mumbai Indians,0,4,MM Patel,Wankhede Stadium,Asad Rauf,SJA Taufel,NaN
71970,305,2,Mumbai Indians,Kolkata Knight Riders,19,6,Harbhajan Singh,JEC Franklin,B Lee,0,...,normal,0,Mumbai Indians,0,4,MM Patel,Wankhede Stadium,Asad Rauf,SJA Taufel,NaN
71971,305,2,Mumbai Indians,Kolkata Knight Riders,20,1,JEC Franklin,Harbhajan Singh,Shakib Al Hasan,0,...,normal,0,Mumbai Indians,0,4,MM Patel,Wankhede Stadium,Asad Rauf,SJA Taufel,NaN
71972,305,2,Mumbai Indians,Kolkata Knight Riders,20,2,Harbhajan Singh,JEC Franklin,Shakib Al Hasan,0,...,normal,0,Mumbai Indians,0,4,MM Patel,Wankhede Stadium,Asad Rauf,SJA Taufel,NaN

In [96]:
merged_data["winner"].unique()

array(['Sunrisers Hyderabad', 'Rising Pune Supergiant',
       'Kolkata Knight Riders', 'Kings XI Punjab',
       'Royal Challengers Bangalore', 'Mumbai Indians',
       'Delhi Daredevils', 'Gujarat Lions', 'Chennai Super Kings',
       'Rajasthan Royals', 'Deccan Chargers', 'Pune Warriors',
       'Kochi Tuskers Kerala', nan, 'Rising Pune Supergiants',
       'Delhi Capitals'], dtype=object)

In [103]:
merged_data[""].unique()

array(['field', 'bat'], dtype=object)

In [105]:
category_counts = merged_data['toss_winner'].value_counts()

# Calculate the percentage
category_percentage = (category_counts / len(merged_data)) * 100

# Create a new DataFrame with counts and percentages
result_df = pd.DataFrame({'Count': category_counts, 'Percentage': category_percentage})

In [106]:
result_df

        Count  Percentage
field  109222     60.9913
bat     69856     39.0087

In [ ]:
merged_data.groupby("toss_winner")[]

In [107]:
merged_data["venue"].value_counts()

Eden Gardens                                            17991
Wankhede Stadium                                        17590
M Chinnaswamy Stadium                                   16872
Feroz Shah Kotla                                        15604
Rajiv Gandhi International Stadium, Uppal               13303
MA Chidambaram Stadium, Chepauk                         12006
Sawai Mansingh Stadium                                  11158
Punjab Cricket Association Stadium, Mohali               8266
Maharashtra Cricket Association Stadium                  5055
Subrata Roy Sahara Stadium                               4064
Dr DY Patil Sports Academy                               3993
Kingsmead                                                3643
Punjab Cricket Association IS Bindra Stadium, Mohali     3315
Sardar Patel Stadium, Motera                             2893
SuperSport Park                                          2866
Brabourne Stadium                                        2719
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium      2546
Saurashtra Cricket Association Stadium                   2381
Himachal Pradesh Cricket Association Stadium             2159
Holkar Cricket Stadium                                   1965
New Wanderers Stadium                                    1940
Rajiv Gandhi Intl. Cricket Stadium                       1912
M. A. Chidambaram Stadium                                1889
Feroz Shah Kotla Ground                                  1701
Dubai International Cricket Stadium                      1700
Barabati Stadium                                         1695
IS Bindra Stadium                                        1690
St George's Park                                         1677
JSCA International Stadium Complex                       1671
Sheikh Zayed Stadium                                     1624
Newlands                                                 1539
M. Chinnaswamy Stadium                                   1531
Sharjah Cricket Stadium                                  1439
Shaheed Veer Narayan Singh International Stadium         1431
Nehru Stadium                                            1155
Green Park                                                921
Vidarbha Cricket Association Stadium, Jamtha              742
De Beers Diamond Oval                                     726
Buffalo Park                                              715
OUTsurance Oval                                           500
ACA-VDCA Stadium                                          491
Name: venue, dtype: int64

In [109]:
merged_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 179078 entries, 0 to 179077
Data columns (total 38 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          179078 non-null  int64
 1   inning            179078 non-null  int64
 2   batting_team      179078 non-null  object
 3   bowling_team      179078 non-null  object
 4   over              179078 non-null  int64
 5   ball              179078 non-null  int64
 6   batsman           179078 non-null  object
 7   non_striker       179078 non-null  object
 8   bowler            179078 non-null  object
 9   is_super_over     179078 non-null  int64
 10  wide_runs         179078 non-null  int64
 11  bye_runs          179078 non-null  int64
 12  legbye_runs       179078 non-null  int64
 13  noball_runs       179078 non-null  int64
 14  penalty_runs      179078 non-null  int64
 15  batsman_runs      179078 non-null  int64
 16  extra_runs        179078 non-null  int64
 17  total_runs        179078 non-null  int64
 18  player_dismissed  8834 non-null    object
 19  dismissal_kind    8834 non-null    object
 20  fielder           6448 non-null    object
 21  season            179078 non-null  int64
 22  city              177378 non-null  object
 23  date              179078 non-null  datetime64[ns]
 24  team1             179078 non-null  object
 25  team2             179078 non-null  object
 26  toss_winner       179078 non-null  object
 27  toss_decision     179078 non-null  object
 28  result            179078 non-null  object
 29  dl_applied        179078 non-null  int64
 30  winner            178706 non-null  object
 31  win_by_runs       179078 non-null  int64
 32  win_by_wickets    179078 non-null  int64
 33  player_of_match   178706 non-null  object
 34  venue             179078 non-null  object
 35  umpire1           178578 non-null  object
 36  umpire2           178578 non-null  object
 37  umpire3           28366 non-null   object
dtypes: datetime64[ns](1), int64(17), object(20)
memory usage: 53.3+ MB

In [128]:
merged_data.loc[(merged_data["toss_decision"] == "field") & (merged_data["toss_winner"] == merged_data["winner"]),"date"].dt.year.value_counts()

2016    7470
2019    7444
2018    6362
2017    6338
2011    6193
2014    5509
2008    4340
2012    4120
2013    3582
2009    3188
2015    3171
2010    2393
Name: date, dtype: int64

In [122]:
merged_data["toss_winner"]

0         Royal Challengers Bangalore
1         Royal Challengers Bangalore
2         Royal Challengers Bangalore
3         Royal Challengers Bangalore
4         Royal Challengers Bangalore
                     ...
179073                 Mumbai Indians
179074                 Mumbai Indians
179075                 Mumbai Indians
179076                 Mumbai Indians
179077                 Mumbai Indians
Name: toss_winner, Length: 179078, dtype: object

In [123]:
merged_data["winner"]

0         Sunrisers Hyderabad
1         Sunrisers Hyderabad
2         Sunrisers Hyderabad
3         Sunrisers Hyderabad
4         Sunrisers Hyderabad
                 ...
179073         Mumbai Indians
179074         Mumbai Indians
179075         Mumbai Indians
179076         Mumbai Indians
179077         Mumbai Indians
Name: winner, Length: 179078, dtype: object

In [140]:
merged_data.loc[(merged_data["date"] == 2019) & (merged_data["batsman_runs"] == 4) | (merged_data["batsman_runs"] == 6), "battsmen"]

10        Yuvraj Singh
47        Yuvraj Singh
75        Yuvraj Singh
89        Yuvraj Singh
91        Yuvraj Singh
              ...
178987       JJ Bumrah
179048       JJ Bumrah
179061       JJ Bumrah
179062       JJ Bumrah
179063       JJ Bumrah
Name: player_of_match, Length: 8170, dtype: object

In [134]:
merged_data["bowler"]

0           TS Mills
1           TS Mills
2           TS Mills
3           TS Mills
4           TS Mills
             ...
179073    SL Malinga
179074    SL Malinga
179075    SL Malinga
179076    SL Malinga
179077    SL Malinga
Name: bowler, Length: 179078, dtype: object

In [135]:
merged_data["dismissal_kind"]

0             NaN
1             NaN
2             NaN
3             NaN
4             NaN
           ...
179073        NaN
179074        NaN
179075    run out
179076        NaN
179077        lbw
Name: dismissal_kind, Length: 179078, dtype: object

In [142]:
merged_data.loc[(merged_data["date"] == 2017) & (merged_data["batting_team"] == "Sunrisers Hyderabad") & (merged_data["bowling_team"] == "Royal Challengers Bangalore") | (merged_data["bowling_team"] == "Sunrisers Hyderabad") & (merged_data["batting_team"] == "Royal Challengers Bangalore"),"player_of_match"].value_counts()

DA Warner         371
AB de Villiers    370
V Kohli           146
GH Vihari         129
BCJ Cutting       124
Yuvraj Singh      123
KS Williamson     123
J Bairstow        123
S Hetmyer         123
Name: player_of_match, dtype: int64

In [147]:
merged_data.loc[(merged_data["dismissal_kind"] == "caught") | (merged_data["dismissal_kind"] == "bowled"),"player_dismissed"].value_counts()

SK Raina      128
V Kohli       125
RG Sharma     125
RV Uthappa    122
G Gambhir     107
             ...
C Madan         1
T Thushara      1
VS Malik        1
KAJ Roach       1
M Santner       1
Name: player_dismissed, Length: 461, dtype: int64

In [143]:
merged_data["dismissal_kind"].unique()

array([nan, 'caught', 'bowled', 'run out', 'lbw', 'caught and bowled',
       'stumped', 'retired hurt', 'hit wicket', 'obstructing the field'],
      dtype=object)

In [154]:
merged_data.loc[(merged_data["batsman"] == "V Kohli") & (merged_data["bowler"] == "JJ Bumrah"),"batsman_runs"]

2633      0
2634      0
2635      1
2637      0
2638      1
         ..
166347    4
166348    4
166349    4
166406    1
166408    0
Name: batsman_runs, Length: 73, dtype: int64

In [148]:
merged_data["batsman"].unique()

array(['DA Warner', 'S Dhawan', 'MC Henriques', 'Yuvraj Singh',
       'DJ Hooda', 'BCJ Cutting', 'CH Gayle', 'Mandeep Singh', 'TM Head',
       'KM Jadhav', 'SR Watson', 'Sachin Baby', 'STR Binny', 'S Aravind',
       'YS Chahal', 'TS Mills', 'A Choudhary', 'PA Patel', 'JC Buttler',
       'RG Sharma', 'N Rana', 'AT Rayudu', 'KH Pandya', 'KA Pollard',
       'HH Pandya', 'TG Southee', 'AM Rahane', 'MA Agarwal', 'SPD Smith',
       'BA Stokes', 'MS Dhoni', 'JJ Roy', 'BB McCullum', 'SK Raina',
       'AJ Finch', 'KD Karthik', 'G Gambhir', 'CA Lynn', 'MK Tiwary',
       'DT Christian', 'HM Amla', 'M Vohra', 'WP Saha', 'AR Patel',
       'GJ Maxwell', 'DA Miller', 'Vishnu Vinod', 'Iqbal Abdulla',
       'P Negi', 'AP Tare', 'SW Billings', 'KK Nair', 'SV Samson',
       'RR Pant', 'CH Morris', 'CR Brathwaite', 'PJ Cummins', 'A Mishra',
       'S Nadeem', 'Z Khan', 'DR Smith', 'DS Kulkarni', 'P Kumar',
       'Basil Thampi', 'RV Uthappa', 'MK Pandey', 'YK Pathan', 'SA Yadav',
       'CR Woakes', 'SP Narine', 'Harbhajan Singh', 'AB de Villiers',
       'CJ Anderson', 'F du Plessis', 'RA Tripathi', 'R Bhatia',
       'DL Chahar', 'A Zampa', 'AB Dinda', 'Imran Tahir', 'NV Ojha',
       'V Shankar', 'Rashid Khan', 'B Kumar', 'MP Stoinis', 'MM Sharma',
       'VR Aaron', 'V Kohli', 'MJ McClenaghan', 'Ankit Sharma',
       'SN Thakur', 'RD Chahar', 'LH Ferguson', 'C de Grandhomme',
       'Bipul Sharma', 'SS Iyer', 'EJG Morgan', 'KC Cariappa',
       'Sandeep Sharma', 'Ishan Kishan', 'JD Unadkat', 'AF Milne',
       'S Badree', 'AD Mathews', 'Mohammed Shami', 'Mohammad Nabi',
       'I Sharma', 'RA Jadeja', 'AJ Tye', 'KS Williamson', 'SE Marsh',
       'Shakib Al Hasan', 'JP Faulkner', 'MG Johnson', 'K Rabada',
       'AD Nath', 'NM Coulter-Nile', 'Kuldeep Yadav', 'UT Yadav',
       'Washington Sundar', 'KV Sharma', 'DM Bravo', 'AR Bawne',
       'SP Jackson', 'MJ Guptill', 'Anureet Singh', 'IK Pathan',
       'Ankit Soni', 'JJ Bumrah', 'SL Malinga', 'PJ Sangwan', 'S Kaul',
       'LMP Simmons', 'MN Samuels', 'Swapnil Singh', 'R Tewatia',
       'MM Patel', 'SS Tiwary', 'TA Boult', 'CJ Jordan', 'IR Jaggi',
       'PP Chawla', 'AS Rajpoot', 'SC Ganguly', 'RT Ponting', 'DJ Hussey',
       'Mohammad Hafeez', 'R Dravid', 'W Jaffer', 'JH Kallis', 'CL White',
       'MV Boucher', 'B Akhil', 'AA Noffke', 'SB Joshi', 'ML Hayden',
       'MEK Hussey', 'JDP Oram', 'S Badrinath', 'K Goel', 'JR Hopes',
       'KC Sangakkara', 'SM Katich', 'T Kohli', 'M Kaif', 'DS Lehmann',
       'M Rawat', 'D Salunkhe', 'SK Warne', 'SK Trivedi', 'V Sehwag',
       'L Ronchi', 'ST Jayasuriya', 'DJ Thornely', 'PR Shah', 'AM Nayar',
       'SM Pollock', 'S Chanderpaul', 'LRPL Taylor', 'AC Gilchrist',
       'Y Venugopal Rao', 'VVS Laxman', 'A Symonds', 'SB Styris',
       'AS Yadav', 'SB Bangar', 'WPUJC Vaas', 'RP Singh', 'LR Shukla',
       'DPMD Jayawardene', 'S Sohal', 'B Lee', 'WA Mota', 'Kamran Akmal',
       'Shahid Afridi', 'DJ Bravo', 'MA Khote', 'A Nehra', 'GC Smith',
       'Pankaj Singh', 'RR Sarwan', 'S Sreesanth', 'VRV Singh',
       'R Vinay Kumar', 'AB Agarkar', 'M Kartik', 'Shoaib Malik',
       'MF Maharoof', 'VY Mahesh', 'TM Srivastava', 'B Chipli',
       'DW Steyn', 'DB Das', 'HH Gibbs', 'DNT Zoysa', 'D Kalyankrishna',
       'SA Asnodkar', 'Sohail Tanvir', 'Salman Butt', 'BJ Hodge',
       'Umar Gul', 'SP Fleming', 'S Vidyut', 'JA Morkel', 'LPC Silva',
       'DB Ravi Teja', 'Misbah-ul-Haq', 'YV Takawale', 'RR Raje',
       'Mohammad Asif', 'GD McGrath', 'Joginder Sharma', 'MS Gony',
       'M Muralitharan', 'M Ntini', 'DT Patil', 'A Kumble', 'S Anirudha',
       'CK Kapugedera', 'A Chopra', 'T Taibu', 'J Arunkumar', 'PP Ojha',
       'SP Goswami', 'SR Tendulkar', 'U Kaul', 'TM Dilshan',
       'AD Mascarenhas', 'Niraj Patel', 'LA Pomersbach', 'Younis Khan',
       'PM Sarvesh Kumar', 'DP Vijaykumar', 'Shoaib Akhtar',
       'Abdur Razzak', 'H Das', 'SD Chitnis', 'CRD Fernando',
       'VS Yeligati', 'L Balaji', 'A Mukund', 'RR Powar', 'JP Duminy',
       'A Flintoff', 'T Thushara', 'JD Ryder', 'KP Pietersen',
       'T Henderson', 'Kamran Khan', 'RS Bopara', 'R Bishnoi',
       'FH Edwards', 'PC Valthaty', 'RJ Quiney', 'AS Raut',
       'Yashpal Singh', 'M Manhas', 'AA Bilakhia', 'AN Ghosh',
       'BAW Mendis', 'DL Vettori', 'MN van Wyk', 'RE van der Merwe',
       'TL Suman', 'Shoaib Ahmed', 'GR Napier', 'KP Appanna',
       'LA Carseldine', 'SM Harwood', 'M Vijay', 'SB Jakati', 'RJ Harris',
       'D du Preez', 'M Morkel', 'J Botha', 'C Nanda', 'Mashrafe Mortaza',
       'A Singh', 'GJ Bailey', 'AB McDonald', 'Y Nagar', 'SS Shaikh',
       'R Ashwin', 'Mohammad Ashraful', 'CA Pujara', 'OA Shah',
       'Anirudh Singh', 'Jaskaran Singh', 'R Sathish', 'R McLaren',
       'AA Jhunjhunwala', 'P Dogra', 'A Uniyal', 'MS Bisla', 'YA Abdulla',
       'JM Kemp', 'S Tyagi', 'RS Gavaskar', 'SE Bond', 'S Ladda',
       'DP Nannes', 'MJ Lumb', 'DR Martyn', 'S Narwal', 'AB Barath',
       'FY Fazal', 'AC Voges', 'MD Mishra', 'J Theron', 'SJ Srivastava',
       'R Sharma', 'SW Tait', 'KB Arun Karthik', 'KAJ Roach',
       'PD Collingwood', 'CK Langeveldt', 'VS Malik', 'A Mithun',
       'AP Dole', 'AN Ahmed', 'RS Sodhi', 'DE Bollinger', 'S Sriram',
       'B Sumanth', 'C Madan', 'AG Paunikar', 'MR Marsh', 'Harmeet Singh',
       'RV Gomez', 'AUK Pathan', 'UBT Chand', 'DJ Jacobs', 'Sunny Singh',
       'NJ Rimmington', 'AL Menaria', 'WD Parnell', 'JJ van der Wath',
       'R Ninan', 'MS Wade', 'TD Paine', 'SB Wagh', 'AC Thomas',
       'JEC Franklin', 'DH Yagnik', 'S Randiv', 'BJ Haddin',
       'NLTC Perera', 'NL McCullum', 'JE Taylor', 'J Syed Mohammad',
       'RN ten Doeschate', 'TR Birt', 'AG Murtaza', 'Harpreet Singh',
       'M Klinger', 'AC Blizzard', 'I Malhotra', 'L Ablish', 'CA Ingram',
       'P Parameswaran', 'CJ Ferguson', 'AA Chavan', 'ND Doshi',
       'Y Gnaneswara Rao', 'S Rana', 'BA Bhatt', 'RE Levi', 'KK Cooper',
       'HV Patel', 'DAJ Bracewell', 'DJ Harris', 'GB Hogg', 'RR Bhatkal',
       'CJ McKay', 'N Saini', 'Azhar Mahmood', 'RJ Peterson',
       'KMDN Kulasekara', 'A Ashish Reddy', 'V Pratap Singh',
       'BB Samantray', 'MJ Clarke', 'Gurkeerat Singh', 'AP Majumdar',
       'PA Reddy', 'K Upadhyay', 'P Awana', 'AD Russell', 'A Chandila',
       'Sunny Gupta', 'MC Juneja', 'GH Vihari', 'MDKJ Perera', 'R Shukla',
       'B Laughlin', 'BMAJ Mendis', 'R Rampaul', 'SMSM Senanayake',
       'BJ Rohrer', 'KL Rahul', 'Q de Kock', 'R Dhawan', 'LJ Wright',
       'IC Pandey', 'CM Gautam', 'X Thalaivan Sargunam', 'DJG Sammy',
       'KW Richardson', 'UA Birla', 'Parvez Rasool', 'PV Tambe',
       'NJ Maddinson', 'JDS Neesham', 'MA Starc', 'BR Dunk', 'RR Rossouw',
       'Shivam Sharma', 'VH Zol', 'BE Hendricks', 'S Gopal', 'M de Lange',
       'JO Holder', 'Karanveer Singh', 'SA Abbott', 'J Suchith',
       'RG More', 'D Wiese', 'SN Khan', 'DJ Muthuswami', 'C Munro',
       'P Sahu', 'KJ Abbott', 'M Ashwin', 'NS Naik', 'PSP Handscomb',
       'J Yadav', 'UT Khawaja', 'F Behardien', 'BB Sran', 'S Kaushik',
       'ER Dwivedi', 'E Lewis', 'M Wood', 'R Singh', 'D Short',
       'K Gowtham', 'T Curran', 'M Markande', 'B Stanlake', 'M Ur Rahman',
       'A Dananjaya', 'S Gill', 'S Mavi', 'Mohammed Siraj', 'H Klaasen',
       'R Bhui', 'J Archer', 'P Shaw', 'L Plunkett', 'Mustafizur Rahman',
       'A Hales', 'M Lomror', 'D Shorey', 'M Ali', 'P Krishna',
       'P Chopra', 'J Searles', 'I Sodhi', 'S Hetmyer', 'S Dube',
       'J Bairstow', 'C Ingram', 'K Paul', 'R Salam', 'N Pooran',
       'N Naik', 'H Vihari', 'P R Barman', 'S Curran', 'H Viljoen',
       'Avesh Khan', 'S Lamichhane', 'S Sharma', 'H Gurney', 'SD Lad',
       'A Joseph', 'R Parag', 'M Santner', 'J Denly', 'L Livingstone',
       'K Ahmed', 'A Turner', 'H Brar', 'S Rutherford', 'P Raj',
       'S Singh'], dtype=object)

In [149]:
merged_data["bowler"].unique()

array(['TS Mills', 'A Choudhary', 'YS Chahal', 'S Aravind', 'SR Watson',
       'TM Head', 'STR Binny', 'A Nehra', 'B Kumar', 'BCJ Cutting',
       'Rashid Khan', 'DJ Hooda', 'MC Henriques', 'Bipul Sharma',
       'AB Dinda', 'DL Chahar', 'BA Stokes', 'Imran Tahir', 'A Zampa',
       'R Bhatia', 'TG Southee', 'HH Pandya', 'MJ McClenaghan',
       'JJ Bumrah', 'KH Pandya', 'KA Pollard', 'TA Boult', 'PP Chawla',
       'SP Narine', 'CR Woakes', 'Kuldeep Yadav', 'YK Pathan', 'P Kumar',
       'DS Kulkarni', 'MS Gony', 'S Kaushik', 'DR Smith', 'SB Jakati',
       'Sandeep Sharma', 'MM Sharma', 'AR Patel', 'T Natarajan',
       'MP Stoinis', 'Swapnil Singh', 'DT Christian', 'RD Chahar',
       'Z Khan', 'CH Morris', 'PJ Cummins', 'S Nadeem', 'A Mishra',
       'CR Brathwaite', 'B Stanlake', 'Iqbal Abdulla', 'P Negi',
       'SK Raina', 'Tejas Baroka', 'Basil Thampi', 'SL Malinga',
       'Harbhajan Singh', 'AS Rajpoot', 'VR Aaron', 'CJ Anderson',
       'Mustafizur Rahman', 'UT Yadav', 'C de Grandhomme', 'I Sharma',
       'GJ Maxwell', 'S Badree', 'AJ Tye', 'RA Jadeja', 'Ankit Sharma',
       'LH Ferguson', 'SN Thakur', 'KC Cariappa', 'MM Patel', 'AF Milne',
       'JD Unadkat', 'NM Coulter-Nile', 'Mohammed Shami', 'AD Mathews',
       'BB Sran', 'S Kaul', 'Mohammad Nabi', 'J Yadav', 'Mohammed Siraj',
       'Yuvraj Singh', 'JP Faulkner', 'Shakib Al Hasan', 'K Rabada',
       'MG Johnson', 'Washington Sundar', 'SS Agarwal', 'NB Singh',
       'KV Sharma', 'RA Tripathi', 'Ankit Soni', 'Anureet Singh',
       'IK Pathan', 'PJ Sangwan', 'MN Samuels', 'MJ Henry', 'R Tewatia',
       'R Vinay Kumar', 'Avesh Khan', 'HV Patel', 'CJ Jordan',
       'AA Noffke', 'JH Kallis', 'SB Joshi', 'CL White', 'AB Agarkar',
       'SC Ganguly', 'LR Shukla', 'B Lee', 'S Sreesanth', 'JR Hopes',
       'K Goel', 'WA Mota', 'JDP Oram', 'M Muralitharan', 'P Amarnath',
       'Joginder Sharma', 'GD McGrath', 'B Geeves', 'MF Maharoof',
       'DL Vettori', 'SK Trivedi', 'SK Warne', 'D Salunkhe', 'B Akhil',
       'SM Pollock', 'ST Jayasuriya', 'AM Nayar', 'M Kartik',
       'Mohammad Hafeez', 'DJ Hussey', 'WPUJC Vaas', 'RP Singh',
       'SB Styris', 'SB Bangar', 'A Symonds', 'PP Ojha', 'Pankaj Singh',
       'Mohammad Asif', 'VY Mahesh', 'Shahid Afridi', 'DJ Bravo',
       'VS Yeligati', 'MA Khote', 'D Kalyankrishna', 'VRV Singh',
       'Sohail Tanvir', 'A Kumble', 'DNT Zoysa', 'SD Chitnis',
       'Shoaib Malik', 'DW Steyn', 'JA Morkel', 'CRD Fernando', 'V Kohli',
       'V Sehwag', 'Gagandeep Singh', 'Y Venugopal Rao', 'Umar Gul',
       'M Ntini', 'DP Vijaykumar', 'DB Ravi Teja', 'LPC Silva',
       'DJ Thornely', 'RR Raje', 'S Vidyut', 'L Balaji', 'CK Kapugedera',
       'AD Mascarenhas', 'Shoaib Akhtar', 'RR Powar', 'PM Sarvesh Kumar',
       'Abdur Razzak', 'TM Dilshan', 'RG Sharma', 'A Nel', 'BAW Mendis',
       'T Thushara', 'A Flintoff', 'Kamran Khan', 'T Henderson',
       'JD Ryder', 'DP Nannes', 'AM Salvi', 'YA Abdulla', 'VS Malik',
       'FH Edwards', 'Harmeet Singh', 'CH Gayle', 'KP Pietersen',
       'LRPL Taylor', 'RS Bopara', 'MK Tiwary', 'RR Bose', 'KP Appanna',
       'Shoaib Ahmed', 'BJ Hodge', 'SR Tendulkar', 'RE van der Merwe',
       'JP Duminy', 'S Tyagi', 'GR Napier', 'SM Harwood', 'AS Raut',
       'D du Preez', 'RJ Harris', 'TL Suman', 'A Singh', 'M Morkel',
       'LA Carseldine', 'A Mithun', 'C Nanda', 'SS Sarkar', 'AM Rahane',
       'J Botha', 'Mashrafe Mortaza', 'AB McDonald', 'Y Nagar',
       'CK Langeveldt', 'R Ashwin', 'RA Shaikh', 'Jaskaran Singh',
       'SW Tait', 'A Uniyal', 'AA Jhunjhunwala', 'R McLaren',
       'AG Murtaza', 'R Sathish', 'RS Gavaskar', 'JM Kemp', 'S Ladda',
       'SE Bond', 'S Narwal', 'SJ Srivastava', 'AC Voges', 'R Sharma',
       'J Theron', 'NLTC Perera', 'KAJ Roach', 'PD Collingwood',
       'C Ganapathy', 'MB Parmar', 'SB Wagh', 'DE Bollinger', 'AP Dole',
       'AN Ahmed', 'FY Fazal', 'MR Marsh', 'L Ablish', 'S Sriram',
       'AJ Finch', 'ND Doshi', 'S Randiv', 'AL Menaria', 'AUK Pathan',
       'RV Gomez', 'JEC Franklin', 'AC Thomas', 'WD Parnell', 'M Manhas',
       'NJ Rimmington', 'RN ten Doeschate', 'BA Bhatt', 'JJ van der Wath',
       'R Ninan', 'PC Valthaty', 'S Dhawan', 'J Syed Mohammad',
       'NL McCullum', 'JE Taylor', 'KMDN Kulasekara', 'P Parameswaran',
       'I Malhotra', 'B Chipli', 'AA Kazi', 'Anand Rajan', 'P Prasanth',
       'Y Gnaneswara Rao', 'AA Chavan', 'S Rana', 'SS Mundhe', 'RW Price',
       'M de Lange', 'KK Cooper', 'DAJ Bracewell', 'DJ Harris',
       'TP Sudhindra', 'F du Plessis', 'GB Hogg', 'RR Bhatkal', 'P Awana',
       'V Pratap Singh', 'CJ McKay', 'AD Russell', 'A Ashish Reddy',
       'Azhar Mahmood', 'A Chandila', 'LJ Wright', 'RJ Peterson',
       'R Shukla', 'MJ Clarke', 'BW Hilfenhaus', 'SPD Smith',
       'K Upadhyay', 'Sunny Gupta', 'B Laughlin', 'GH Vihari',
       'BMAJ Mendis', 'Harmeet Singh (2)', 'R Dhawan', 'R Rampaul',
       'SMSM Senanayake', 'JO Holder', 'IC Pandey', 'DJG Sammy',
       'KW Richardson', 'P Suyal', 'PV Tambe', 'BJ Rohrer',
       'Parvez Rasool', 'MG Neser', 'AC Gilchrist', 'MA Starc',
       'JDS Neesham', 'M Vijay', 'SA Yadav', 'Shivam Sharma', 'V Shankar',
       'LMP Simmons', 'K Santokie', 'S Gopal', 'BE Hendricks',
       'JW Hastings', 'Karanveer Singh', 'DJ Muthuswami', 'SA Abbott',
       'J Suchith', 'RG More', 'D Wiese', 'GS Sandhu', 'Gurkeerat Singh',
       'M Ashwin', 'C Munro', 'P Sahu', 'KJ Abbott', 'T Shamsi',
       'SM Boland', 'Sachin Baby', 'N Rana', 'KS Williamson', 'M Wood',
       'M Markande', 'M Ur Rahman', 'K Khejroliya', 'K Gowtham',
       'D Short', 'T Curran', 'A Dananjaya', 'S Mavi', 'J Archer',
       'L Plunkett', 'I Sodhi', 'M Lomror', 'L Ngidi', 'KM Asif',
       'D Willey', 'P Krishna', 'M Ali', 'J Searles', 'S Lamichhane',
       'J Dala', 'K Ahmed', 'N Saini', 'S Dube', 'L Ferguson', 'S Sharma',
       'R Salam', 'K Paul', 'S Curran', 'V Chakravarthy', 'H Viljoen',
       'Mandeep Singh', 'P R Barman', 'M Santner', 'H Vihari',
       'J Behrendorff', 'S Kuggeleijn', 'A Joseph', 'H Gurney',
       'S Midhun', 'R Parag', 'L Livingstone', 'SN Khan', 'S Rutherford',
       'H Brar', 'P Raj', 'O Thomas', 'A Roy', 'S Warrier'], dtype=object)